language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.0"
  #- "3.1"
  #- "3.2"
  #- "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly" # nightly build
install:
  - pip install -r requirements.txt
script: true  # temporary script